stages:
  - test

cache:
  key: composer-cache
  paths:
    - .composer-cache/

.test:
  before_script:
    # install system packages
    - apt-get update && apt-get install -y git unzip
    # install composer
    - php -r "copy('https://composer.github.io/installer.sig', '/tmp/composer.sig');"
    - php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    - php -r '$expected = file_get_contents("/tmp/composer.sig"); $actual = hash_file("sha384", "/tmp/composer-setup.php"); exit(intval(!hash_equals($expected, $actual)));'
    - php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - chmod +x /usr/local/bin/composer
    - rm /tmp/composer-setup.php /tmp/composer.sig
    # cache dependencies
    - composer config -g cache-dir "$(pwd)/.composer-cache"
  script:
    - composer update
    - vendor/bin/phpunit

# main matrix
test:
  extends: .test
  stage: test
  image: php:${PHP_VERSION}
  parallel:
    matrix:
      - PHP_VERSION:
          - '7.1' # lowest version
          - '7' # latest 7
          - '8' # latest 8

# lowest version with lowest dependencies
test-7.1-lowest:
  extends: .test
  stage: test
  image: php:7.1
  script:
    - composer update --prefer-lowest
    - vendor/bin/phpunit
