language: php
php:
  - '7.4'
  - nightly
matrix:
  allow_failures:
    - php: nightly
install:
  - composer install
script:
  # test on latest libs
  - vendor/bin/phpunit
  # test on earliest libs
  - composer update --prefer-lowest
  - vendor/bin/phpunit
